config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get 'users/new'
  root 'static_pages#home'

  get 'static_pages/help'
  get 'static_pages/about'
  get 'static_pages/contact'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  get 'sessions/new'
  post 'sessions/create'
  get 'sessions/destroy'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  
  # Defines the root path route ("/")
  # root "articles#index"

end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		This Page is designed by 
		 <a href="#">Deepak</a>
	</small>
	<nav>
		<ul>
			<li><%= link_to "About",static_pages_about_path%></li>
			<li><%= link_to "Contact",static_pages_contact_path %></li>
			<li><a href="http://news.railstutorial.org/">News</a></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<%= link_to "Sample App", root_path, id: "logo" %>
		<nav>
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "Home",root_path %></li>
				<li><%= link_to "Help",static_pages_help_path %></li>
				<% if logged_in? %>
					<li><%= link_to "Users", users_path %></li>
					<li class="dropdown">
						<a href="#", class="dropdown-toggle", data-toggle="dropdown">Account <b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li><%= link_to "Profile",current_user %></li>
							<li><%= link_to "Settings","#"%></li>
							<li class="divider"></li>

							
						</ul>
							<li>
								<%= link_to "Log out", sessions_destroy_path, method: :delete %>
							</li>
					</li>
					<% else %>
					<li><%= link_to "Log in", sessions_new_path %></li>
				<% end %>
				
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sample App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>